version: 0.0
os: linux
files:
  - source: target/HelloWorld.war
    destination: /var/lib/tomcat9/webapps/

hooks:
  BeforeInstall:
    - location: scripts/clean_webapps.sh
      timeout: 300
      runas: root
