version: 0.0
os: linux
files:
  - source: /HelloWorld.tar.gz
    destination: /var/lib/tomcat9/webapps/

hooks:
  BeforeInstall:
    - location: scripts/clean_webapps.sh
      timeout: 300
  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 300
