version: 0.0
os: linux
files:
  - source:  .
    destination: /var/lib/tomcat9/webapps/helloworld-project

hooks:
  BeforeInstall:
    - location: scripts/clean_webapps.sh
      timeout: 300
      runas: root
